name: CD

on:
  release:
    types:
      - published

jobs:
  cd:
    uses: halo-sigs/reusable-workflows/.github/workflows/plugin-cd.yaml@v3
    permissions:
      contents: write
      packages: read
    secrets:
      halo-pat: ${{ secrets.HALO_PAT }}
    with:
      node-version: "20"
      pnpm-version: "10"
      app-id: "app-hDXMG"

